Add File Manager; New CI [minor] (#45)
Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -1,6 +1,7 @@
 name: wipac ci/cd
 
 on:
+  # only on branch pushes
   push:
     branches:
       - '**'
@@ -29,8 +30,11 @@ jobs:
       matrix: ${{ steps.versions.outputs.matrix }}
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
       - id: versions
-        uses: WIPACrepo/wipac-dev-py-versions-action@v2.5
+        uses: WIPACrepo/wipac-dev-py-versions-action@v2.7
 
 
   #############################################################################
@@ -38,13 +42,23 @@ jobs:
   #############################################################################
 
   flake8:
+    needs: [ py-versions ]
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-      - uses: WIPACrepo/wipac-dev-flake8-action@v1.2
         with:
-          max-complexity: 12
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+      - uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.py3 }}
+      - uses: WIPACrepo/wipac-dev-flake8-action@v1.3
+        with:
+          max-complexity: 13  # ideal is ~10-15
 
   mypy:
     needs: [ py-versions ]
@@ -55,6 +69,9 @@ jobs:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit ('github.ref is dynamic)
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.py3 }}
@@ -65,62 +82,37 @@ jobs:
   # PACKAGING
   #############################################################################
 
-  writable-branch-detect:
-    runs-on: ubuntu-latest
-    outputs:
-      OKAY: ${{ steps.detect.outputs.OKAY }}
-    steps:
-      - name: is this a bot-writable branch?
-        id: detect
-        # dependabot can't access normal secrets
-        #   & don't run non-branch triggers (like tags)
-        #   & we don't want to trigger an update on PR's merge to main/master/default (which is a branch)
-        run: |
-          set -euo pipefail
-          if [[ \
-              ${{github.actor}} != 'dependabot[bot]' && \
-              ${{github.ref_type}} == 'branch' && \
-              ${{format('refs/heads/{0}', github.event.repository.default_branch)}} != ${{github.ref}} \
-          ]]; then
-            echo "OKAY=true" >> "$GITHUB_OUTPUT"
-            echo "yes, this branch is compatible"
-          else
-            echo "OKAY=false" >> "$GITHUB_OUTPUT"
-            echo "no, this branch is incompatible"
-          fi
-
   py-setup:
-    needs: [ writable-branch-detect ]
     runs-on: ubuntu-latest
     steps:
-      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
+          fetch-depth: 0  # setuptools-scm needs to access git tags
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
-        uses: WIPACrepo/wipac-dev-py-setup-action@v3.1
+          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
+      - uses: WIPACrepo/wipac-dev-py-setup-action@v5.3
         with:
-          base-keywords: WIPAC IceCube "Observation Management Service" "Event Workflow Management Service"
+          mode: PACKAGING
+          python_min: 3.11
+          keywords_comma: "WIPAC, IceCube, Observation Management Service, Event Workflow Management System, EWMS, task, Task Management Service"
+          auto_mypy_option: True
 
   py-dependencies:
-    needs: [ writable-branch-detect ]
+    needs: [ flake8 ]
     runs-on: ubuntu-latest
     steps:
-      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
-        uses: docker/setup-buildx-action@v2
-      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
-        uses: docker/build-push-action@v3
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+      - uses: docker/setup-buildx-action@v3
+      - uses: docker/build-push-action@v6
         with:
           context: .
-          file: Dockerfile
+          file: ./Dockerfile
           tags: tms:py-dep-this
           load: true
-      - if: needs.writable-branch-detect.outputs.OKAY == 'true'
-        uses: WIPACrepo/wipac-dev-py-dependencies-action@v2.1
+      - uses: WIPACrepo/wipac-dev-py-dependencies-action@v3.1
 
 
   #############################################################################
@@ -131,6 +123,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
       - uses: docker/setup-buildx-action@v3
       - uses: docker/build-push-action@v6
         with:
@@ -145,6 +140,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
       - uses: docker/setup-buildx-action@v3
       - uses: docker/build-push-action@v6
         with:
@@ -156,7 +154,7 @@ jobs:
           load: true
       - name: install apptainer
         run: |
-          set -euo pipefail
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           set -x
           
           # https://github.com/apptainer/apptainer/blob/main/INSTALL.md#installing-apptainer
@@ -200,12 +198,12 @@ jobs:
           sudo systemctl reload apparmor
       - name: build apptainer image (.sif)
         run: |
-          set -euo pipefail
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           apptainer build $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif docker-daemon://${{ env.DOCKER_IMAGE_NAME }}:local
           ls -lh $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif
       - name: run apptainer container
         run: |
-          set -euo pipefail
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           apptainer run $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif \
             ls
 
@@ -218,23 +216,63 @@ jobs:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.py3 }}
-      - run: |
-          set -euo pipefail
+      - name: pip install
+        run: |
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           pip install .[tests]
-      - run: |
-          set -euo pipefail
+      - name: pytest
+        run: |
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           pytest -vvv tests/unit/
 
+  integration-test-ish:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+      - uses: docker/setup-buildx-action@v3
+      - uses: docker/build-push-action@v6
+        with:
+          context: .
+          cache-from: type=gha
+          cache-to: type=gha,mode=min
+          file: Dockerfile
+          tags: ${{ env.DOCKER_IMAGE_NAME }}:local
+          load: true           # make the image available to `docker run` on this runner
+      - name: test
+        run: |
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -ex
+          
+          docker run --rm \
+              $(env | grep '^EWMS_' | awk '$0="--env "$0') \
+              $(env | grep '^JOB_EVENT_LOG_' | awk '$0="--env "$0') \
+              --env JOB_EVENT_LOG_DIR="/jel/$JOB_EVENT_LOG_DIR" \
+              --mount type=bind,source="$(realpath $JOB_EVENT_LOG_DIR)",target="/jel/$JOB_EVENT_LOG_DIR" \
+              ${{ env.DOCKER_IMAGE_NAME }}:local \
+              2>&1 | tee docker.out || true
+          
+          # check that we get the start up errors that we expect 
+          grep -Fq "htcondor.HTCondorLocateError: Unable to locate local daemon" docker.out || (echo "Not found" && exit 1) 
+          grep -Fq "requests.exceptions.MissingSchema: Invalid URL" docker.out || (echo "Not found" && exit 1)
+          
+          echo "found all the expected startup errors :)"
+
 
   #############################################################################
-  # GITHUB RELEASE
+  # GIT TAG & GITHUB RELEASE
   #############################################################################
 
-  release:
-    # only run on main/master/default
+  tag-and-release:
+    # only run on main/default branch
     if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
     needs: [
       flake8,
@@ -244,18 +282,16 @@ jobs:
       py-dependencies,
       test-build-docker,
       test-build-apptainer,
-      unit-test
+      unit-test,
+      integration-test-ish,
     ]
-    runs-on: ubuntu-latest
-    concurrency: release
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-      - name: Python Semantic Release
-        uses: python-semantic-release/python-semantic-release@v7.34.6
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          # repository_username: __token__
-          # repository_password: ${{ secrets.PYPI_TOKEN }}
+    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/tag-and-release.yml@v1.11
+    permissions: # for GITHUB_TOKEN
+      contents: write
+    with:
+      project-type: python
+      python-version: "${{ fromJSON(needs.py-versions.outputs.matrix)[0] }}"
+      release-artifacts: |
+        py-dependencies-logs
+    secrets:
+      TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # trigger tag-event gha workflows
